#!/usr/bin/env bash
# Open the Fall 2026 gap issues across the estate. Idempotent-ish: skips a repo/title that already exists.
set -u
mk() { # repo title body
  local repo="$1" title="$2" body="$3"
  if gh issue list -R "$repo" --state open --search "\"$title\" in:title" --json title --jq '.[].title' | grep -Fxq "$title"; then echo "skip  $repo :: $title"; return; fi
  gh issue create -R "$repo" --title "$title" --body "$body

Tracked in aigovops-foundation/practice RELEASE.md (train fall-2026). Opened from the 11 Sept end-to-end check." --json url --jq '.url' 2>/dev/null || gh issue create -R "$repo" --title "$title" --body "$body" 
}
O=aigovops-foundation
mk $O/aigovops-library-june-ken-bob "[fall-2026] T10 — JCS canonicalizer (blocks every verifiable-chain claim)" "Day 1 of P0. Root cause of the sign/verify bugs found in T3. Nothing downstream (schema v0.1, gate SDK, receipt chain, offline verifier) is claimable until this is green. Acceptance: one fixture set canonicalizes identically in the Library, Beacon's browser demo and the verifier."
mk $O/aigovops-library-june-ken-bob "[fall-2026] Gate Check page: rule box + action box + four lens tabs (Level 100's decide step)" "Today the level-100 worksheet decides on paper and gets a real receipt from Beacon's demo of a *sample* inventory. P0 makes the decide step real: a rule box (plain words → the three-line YAML, and the reverse), an action box, a decision receipt bound to the payload hash, four lens tabs (engineer/compliance/auditor/regulator), a download, and \`share\` (hash → Gate Card). Default scenario VH-001 Air Canada. Exit test: a stranger closes the 100 loop in under an hour unaided."
mk $O/aigovops-library-june-ken-bob "[fall-2026] Ledger: practice.complete and practice.mark receipts (the credential)" "Opt-in, hash-only. practice.complete = a level loop closed by a key the practitioner controls; practice.mark = a host's mark, host as approver (the C3 hold-and-release shape applied to people). Counted by jeeves numbers with zero identities. See practice/docs/MEMBER-ACTIVITIES.md 'The credential, per level'."
mk $O/umbrella-govops "[fall-2026] First PyPI release (0.1.0) — the README's first install line must work" "\`pipx install umbrella-conformance\` has 404'd since July (README says so). Publish 0.1.0 so the level-200 worksheet's first line works; then add the gate vocabulary (tier, decision, constraints, stop_conditions, default: deny) to the schema and validate it by name in \`check\`."
mk $O/aigovops-lantern "[fall-2026] 0.2.0 — render gate decisions in all four lenses; diff across two gate runs" "Beacon's gate receipts (decision, tier, constraints_applied, stopped_by, degraded, agent_id, authority) render in engineer/compliance/auditor/regulator lenses; \`lantern diff\` narrates what a policy change did between two gate runs (the level-200 'weaken one rule' step). Also: PyPI release so \`pip install aigovops-lantern\` works. Web viewer (#2) becomes the public verify page; GitHub Action (#3) becomes the 200 policy gate."
mk $O/aigovops-beacon "[fall-2026] 0.3.0 — beacon gate check / gate init / share; reconcile versions; first GitHub release" "server/ and studio/ package.json say 0.1.0 while CHANGES-v0.2.md exists and there is no GitHub release. Reconcile to one number, cut a release, then add the P0 surfaces: \`beacon gate check\` (decision + receipt as one act, hash-bound), \`gate init\` (policy.yaml scaffold with tiers), \`share\` (hash → Gate Card). Python SDK (F2) with a documented wire protocol."
mk $O/aigovops-beacon "[fall-2026] README: correct the AAL / IAP roadmap line against OVERT 1.1; keep the profile status honest" "Per OVERT 1.1 (June 2026) the Independent Attestation Provider is an AAL-4 requirement and registered profiles are required from AAL-3; the README's 'AAL-2 with IAP on roadmap' should be re-stated. Until \`aigovops-beacon.v1\` is registered, every public line says *targeting OVERT 1.1 conformance; registration pending*."
mk $O/Omni-Rapp-June-2026 "[fall-2026] jeeves numbers: loops closed and marks minted by level, no names; Tuesday Letter line" "One line for the Letter and the Redesign Plan: practice.complete and practice.mark receipts counted by level (100/200/300/400), zero identities; plus the readiness countdown to 2 Dec 2027 (EU AI Act Annex III, post-Omnibus)."
mk $O/Omni-Rapp-June-2026 "[fall-2026] Thursday run-of-show: first five minutes for receipts; host rota as data" "cohort_call gains the fixed run-of-show (receipts → a 200's diff → a 300's coverage → a 400's verification → marks) and a host rota so a 400 can claim a Thursday. Ken hosts until the first 400 does."
mk $O/practice "[fall-2026] Exit test: one stranger finishes the Level 100 worksheet in under an hour, unaided" "The train leaves when this is true. Recruit one person who has never seen the site; time them; record where they stalled; file each stall as an issue against the worksheet. This issue closes with their name (with permission) and their bundle hash."
mk $O/practice "[fall-2026] Credential criteria, per level, for the Review Circle" "Write the pass criteria for 100–400 as a single document (from docs/MEMBER-ACTIVITIES.md 'The credential, per level'), with the two-sentence person/system rule, and send to the OVERT steward for reading before minting (PRD v3 D10/D11). 100 and 200 by day 20; 300 and 400 by day 60."
mk $O/practice "[fall-2026] Pages: footer with the promise line and the Gate Check link; link-check CI" "The rendered Pages (Primer) carry no way back to the Foundation site and no Gate Check footer, so the site's message-lint discipline does not cover them. Add a minimal layout/footer and a link-check workflow on PRs."
